### ISSUE TITLE
GetPubMedByID appears not to retrieve the last pmid

### ISSUE THREAD

**Issue by dalewsteele** [mwmclean/RefManageR#2]
Great package!   Very possible I'm doing something wrong, however, If I give GetPubMedByID a list of 'n' PMIDs, it returns only the first n-1 references.

pmlist <- c("24977996", "24921111", "24583574", "24420809", "22858745")
length(pmlist)
dwsbib  <- GetPubMedByID(pmlist)
length(dwsbib)

**Comment by mwmclean** [comment]
The issue here is actually that ID "24921111" corresponds to a "Book" entry that GetPubMedByID could not parse.  GetPubMedByID will now correctly parse "Book" entries and will also print a message if there are any ID's that it cannot create entries for.  Fixed by commit 587739375292508fc743f97866de04af990c4e30.

**Comment by dalewsteele** [comment]
Excellent - hadn't considered that possibility.   When I sent a bigger list of PMIDs to GetPubMedByID I get the new very useful warning:
     'Unable to fetch entries for id's: 11678951, 15373863'
FWIW, both of these are Publication Type 'Journal Article', but the xml lists multiple 'publication types'. Not sure how often this happens...
            <PublicationTypeList>
                <PublicationType UI="D016430">Clinical Trial</PublicationType>
                <PublicationType UI="D016428">Journal Article</PublicationType>
                <PublicationType UI="D016449">Randomized Controlled Trial</PublicationType>
            </PublicationTypeList>

**Comment by mwmclean** [comment]
What was happening here is that individual author names are not returned by PudMed for those ID's, so the entries were not added because the required author field was missing for the "Article" bibtype.  I have made a few fixes/improvements at commits 920a0c7dc714da0ac1d3b8d153149ee3501eb3a7 and 07b5487d42d03b11fcb3d3e1ecde83dd2328ab59:
1) That a message was not printed that the entries were missing a required field is due to a bug I introduced a couple commits ago; this is now corrected
2) Though the individual authors are not available, PubMed did return the name of a collective; this is now used as the value for the "author" field when the individual authors are missing
3) If no authors or collective are available, the entry will still be added as bibtype "misc"
