### ISSUE TITLE
GetPubMedByID example now failing

### ISSUE THREAD

**Issue by dalewsteele** [mwmclean/RefManageR#22]
The GetPubMedByID example now fails.  Could this be related to some change at NLM?

```
library(RefManageR)
library(RCurl)
if (interactive() && url.exists("http://eutils.ncbi.nlm.nih.gov/"))
  GetPubMedByID(c("11209037", "21245076"))
```

running the above code returns:

```
Space required after the Public Identifier
SystemLiteral " or ' expected
SYSTEM or PUBLIC, the URI is missing
Error: 1: Space required after the Public Identifier
2: SystemLiteral " or ' expected
3: SYSTEM or PUBLIC, the URI is missing
```

**Comment by anthonycrane** [comment]
The URL in line 8 of the GetPubMedByID function needs to be changed to reflect a change to https on pubmed. If you change it to the following the function works:

`base.url <- "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?`

**Comment by qade544** [comment]
Hi Anthonycrane,
Well, the problem seems still to be existed~~

Show as below:

> aarlist1<-apply(aaiddf, 2, GetPubMedByID)
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Space required after the Public Identifier [65]

Could you give me a hand? Thanks a lot!


Best,
Shisheng

**Comment by mwmclean** [comment]
Can't help without knowing what `aaiddf` is.

**Comment by qade544** [comment]
Sorry for that. aaiddf is a PMID vector having 951 IDs. you could ignore the aaid. Show as below:

> aaiddf<-data.frame(ID=aaid,stringsAsFactors = FALSE)
> dim(aaiddf)
[1] 951   1
> head(aaiddf)
        ID
1 29300686
2 29294594
3 29270791
4 29263872
5 29260681
6 29260672

when I analyze these 951 IDs once, it occured this kind of error, however, I split it into two part, it was OK! As below:

##One part:
aaiddf<-data.frame(ID=aaid[1:400],stringsAsFactors = FALSE)
> aarlist11<-apply(aaiddf, 2, GetPubMedByID)
Ignoring entry 'zhousudden'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'malikgeneration'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'wangcardiac'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'yufungal'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'liperceptions'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'zhangleveraging'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'cuiimmune'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'wiwanitkitstructural'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Unable to fetch entries for id's: 28409054, 27934828, 27912070, 27819134, 27757257, 26306219, 25926242, 25709350
##################################
####Second part:
> aaiddf<-data.frame(ID=aaid[401:900],stringsAsFactors = FALSE)
> aarlist11<-apply(aaiddf, 2, GetPubMedByID)
Ignoring entry 'arimaauthor'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'joobh7n9'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'zhanghuman'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'wiwanitkitthrombohemostatic'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'wiwanitkitaletter'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'fungefficient'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry '2014fast'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: author

Ignoring entry '2014'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: author

Ignoring entry 'haradaavian'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'murhekaravian'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'arimahuman'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry '2013guideline'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: author

Ignoring entry 'povedarisk'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry 'luoutbreak'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: c("year", "date")

Ignoring entry '2013h7n9'  because:
	A bibentry of bibtype ‘Article’ has to specify the field: author

Unable to fetch entries for id's: 25360327, 26842141, 25076443, 25031066, 24478920, 24478916, 26052590, 25789365, 24015371, 24015364, 24015363, 23977439, 23847792, 23806878, 23804183
Warning messages:
1: Incomplete list of authors returned by PubMed for ID: 26052590 
2: Incomplete list of authors returned by PubMed for ID: 25789365 
3: Incomplete list of authors returned by PubMed for ID: 23977439 
4: Incomplete list of authors returned by PubMed for ID: 23804183 

It works! Also ignore these warning information~~


Shisheng

**Comment by mwmclean** [comment]
Thanks for your reply.  Why are you creating a data.frame and using `apply()`?  Why not just `GetPubMedByID(aaid)`?

If you want to add those entries that you are getting messages "Ignoring entry ..." about, you can use
`BibOptions(check.entries = FALSE)` before calling `getPubMedByID()`.

If you still have a problem you'd like me to take a look at, please open a new [issue](https://github.com/ropensci/RefManageR/issues) and provide an example I can reproduce on my machine.

**Comment by qade544** [comment]
Yeah, Thanks a lot. I tried GetPubMedByID(aaid) at the first time, but it gave me an error: Space required after the Public Identifier, so I want to try it one by one^_^. Yes, I will optimize my codes later.
